In [16]:
# import lib 

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder,OrdinalEncoder

In [17]:
# load the data 
df = sns.load_dataset('titanic')
df.head()

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [ ]:
# impute missing values 

df['age'].fillna(df['age'].median(), inplace=True)
df['age'].fillna(df['age'].median(), inplace=True)
df['embark_town'].fillna(df['embark_town'].mode()[0], inplace=True)
df.drop('deck', axis=1, inplace=True)

In [19]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    str
 12  alive        891 non-null    str
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(5)
memory usage: 79.4 KB

In [20]:
# encode all cat variable and object
le_sex = LabelEncoder()
le_embarked = LabelEncoder()
le_who = LabelEncoder()
le_embark_town = LabelEncoder()
le_alive = LabelEncoder()
le_alone = LabelEncoder()
le_adult_male = LabelEncoder()
le_class = LabelEncoder()
# oe = OneHotEncoder()

df['sex'] = le_sex.fit_transform(df['sex'])
df['embarked'] = le_embarked.fit_transform(df['embarked'])
df['who'] = le_who.fit_transform(df['who'])
df['embark_town'] = le_embark_town.fit_transform(df['embark_town'])
df['alive'] = le_alive.fit_transform(df['alive'])
df['alone'] = le_alone.fit_transform(df['alone'])
df['adult_male'] = le_adult_male.fit_transform(df['adult_male'])
df['class'] = le_class.fit_transform(df['class'])
df.head()

   survived  pclass  sex   age  ...  adult_male  embark_town  alive  alone
0         0       3    1  22.0  ...           1            2      0      0
1         1       1    0  38.0  ...           0            0      1      0
2         1       3    0  26.0  ...           0            2      1      1
3         1       1    0  35.0  ...           0            2      1      0
4         0       3    1  35.0  ...           1            2      0      1

[5 rows x 14 columns]

In [21]:
# inverse tranform 

df['sex'] = le_sex.inverse_transform(df['sex'])
df['embarked'] = le_embarked.inverse_transform(df['embarked'])
df['who'] = le_who.inverse_transform(df['who'])
df['embark_town'] = le_embark_town.inverse_transform(df['embark_town'])
df['alive'] = le_alive.inverse_transform(df['alive'])
df['alone'] = le_alone.inverse_transform(df['alone'])
df['adult_male'] = le_adult_male.inverse_transform(df['adult_male'])
df['class'] = le_class.inverse_transform(df['class'])
df.head()

   survived  pclass     sex   age  ...  adult_male  embark_town  alive  alone
0         0       3    male  22.0  ...        True  Southampton     no  False
1         1       1  female  38.0  ...       False    Cherbourg    yes  False
2         1       3  female  26.0  ...       False  Southampton    yes   True
3         1       1  female  35.0  ...       False  Southampton    yes  False
4         0       3    male  35.0  ...        True  Southampton     no   True

[5 rows x 14 columns]